local name, ns = ...
local L = ns.L

L["LKEY_OPTIONS_TITLE"] = name .. " " .. "Options"

L["LKEY_OPTIONS_POSITION_TITLE"] = "Position"
L["LKEY_OPTIONS_LOCKED_CB"] = "Lock Frame"

L["LKEY_OPTIONS_BACKDROP_TITLE"] = "Backdrop"
L["LKEY_OPTIONS_BACKDROP_CB"] = "Enable Backdrop"

L["LKEY_OPTIONS_DYNAMIC_WIDTH_TITLE"] = "Width"
L["LKEY_OPTIONS_DYNAMIC_WIDTH_CB"] = "Enable Dynamic Width"
L["LKEY_OPTIONS_STATIC_WIDTH_EB"] = "Static Width (min 50): "

L["LKEY_OPTIONS_FONT_SIZE_TITLE"] = "Font Size"
L["LKEY_OPTIONS_FONT_SIZE_EB"] = "Font Size (min 8): "

L["LKEY_OPTIONS_FONT_ALIGNMENT_TITLE"] = "Font Alignment"
L["LKEY_OPTIONS_FONT_ALIGNMENT_LEFT"] = "Left"
L["LKEY_OPTIONS_FONT_ALIGNMENT_CENTER"] = "Center"
L["LKEY_OPTIONS_FONT_ALIGNMENT_RIGHT"] = "Right"

L["LKEY_OPTIONS_SESSION_TITLE"] = "Session"
L["LKEY_OPTIONS_AUTO_CLEAN_TITLE"] = "Auto Clean Frequency"
L["LKEY_OPTIONS_CLEAN_FREQ_SESSION"] = "SESSION"
L["LKEY_OPTIONS_CLEAN_FREQ_DAILY"] = "DAILY"
L["LKEY_OPTIONS_CLEAN_FREQ_NEVER"] = "NEVER"

L["LKEY_OPTIONS_FADE_TITLE"] = "Fade"
L["LKEY_OPTIONS_FADE_CB"] = "Enable Fade Effect"
L["LKEY_OPTIONS_FADE_OUT_OPACITY_SLIDER"] = "Fade Out Opacity"
L["LKEY_OPTIONS_FADE_IN_OPACITY_SLIDER"] = "Fade In Opacity"
L["LKEY_OPTIONS_FADE_DURATION_EB"] = "Fade Duration (seconds): "

L["LKEY_TOTAL_CHAT_HISTORY"] = "Total"

L["LKEY_CLEARING_DAILY_SESSION"] = "Clearing daily session: "
L["LKEY_CLEARED"] = " cleared."